# Generated by Django 5.2.17 on 2026-08-27 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('mediahub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('og_title', models.CharField(blank=True, max_length=180)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.URLField(blank=True, max_length=500)),
                ('schema_type', models.CharField(choices=[('Product', 'Product'), ('Article', 'Article'), ('CollectionPage', 'Collection page'), ('WebPage', 'Web page')], default='WebPage', max_length=32)),
                ('primary_keyword', models.CharField(blank=True, max_length=120)),
                ('secondary_keywords', models.JSONField(blank=True, default=list)),
                ('seo_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('seo_issues', models.JSONField(blank=True, default=list)),
                ('seo_checked_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('body', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ai_generated', 'AI generated'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('content_origin', models.CharField(choices=[('human', 'Human authored'), ('ai_generated', 'AI generated'), ('ai_assisted', 'AI assisted'), ('human_edited', 'Human edited'), ('human_approved', 'Human approved')], default='human', max_length=20)),
                ('date_published', models.DateField(blank=True, db_index=True, null=True)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediahub.mediaasset')),
                ('related_categories', models.ManyToManyField(blank=True, related_name='articles', to='catalog.category')),
            ],
            options={
                'ordering': ['-date_published', '-created_at'],
            },
        ),
    ]
