# Generated by Django 5.2.17 on 2026-08-27 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('trading_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sales_email', models.EmailField(blank=True, max_length=254)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('address_building', models.CharField(blank=True, max_length=200)),
                ('address_street', models.CharField(blank=True, max_length=200)),
                ('address_locality', models.CharField(blank=True, max_length=120)),
                ('address_region', models.CharField(blank=True, max_length=120)),
                ('address_country', models.CharField(blank=True, max_length=120)),
                ('address_country_code', models.CharField(blank=True, max_length=4)),
                ('postal_address', models.CharField(blank=True, max_length=200)),
                ('default_seo_title_suffix', models.CharField(blank=True, max_length=120)),
                ('default_meta_description', models.CharField(blank=True, max_length=320)),
            ],
            options={
                'verbose_name_plural': 'company settings',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kind', models.CharField(choices=[('quote', 'Quote request'), ('contact', 'General enquiry')], default='quote', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('quoted', 'Quoted'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('product_text', models.CharField(blank=True, max_length=300)),
                ('quantity', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='business_in_status_198bc0_idx')],
            },
        ),
    ]
